import type { SiteSnapshot } from "./types";

export const fallbackSnapshot: SiteSnapshot = {
  settings: {
    name: "Motion Intelligence Lab",
    short_name: "MI Lab",
    tagline: "We build intelligent machines that learn to move safely in the real world.",
    description:
      "Our lab studies the intersection of robot learning, embodied intelligence, and dependable autonomy. We build systems that can reason about motion, adapt to new environments, and collaborate with people.",
    location: "School of Engineering · Shanghai",
    email: "hello@motionlab.example",
    visit_count: 0,
    started_at: null,
    hero_kicker: "Robotics · Learning · Trust",
    hero_image_url: "/reference/lab-dinner.jpg",
    google_scholar_url: "https://scholar.google.com/",
    github_url: "https://github.com/",
  },
  news: [
    {
      id: 1,
      date: "2026-08-18",
      title: "New preprint available",
      body: "Our new work on uncertainty-aware visuomotor policies is now available as a preprint.",
      href: "#publications",
      tag: "Publication",
    },
    {
      id: 2,
      date: "2026-07-04",
      title: "Best Paper Award at RoboLearn 2026",
      body: "Congratulations to the team for receiving the Best Paper Award for Safe Policy Improvement with World Models.",
      href: "#",
      tag: "Award",
    },
    {
      id: 3,
      date: "2026-06-12",
      title: "We are welcoming new students",
      body: "Applications are open for motivated students interested in robot learning and embodied intelligence.",
      href: "/join",
      tag: "Lab",
    },
    {
      id: 4,
      date: "2026-04-22",
      title: "The lab is growing",
      body: "Three new members have joined our group to work on dexterous manipulation and safe navigation.",
      href: "/people",
      tag: "People",
    },
  ],
  research: [
    {
      id: 1,
      kicker: "01 · Learn",
      title: "World models for action",
      description:
        "Predictive representations that connect perception, language, and action so robots can plan before they move.",
      accent: "red",
    },
    {
      id: 2,
      kicker: "02 · Adapt",
      title: "Generalizable manipulation",
      description:
        "Learning skills that transfer across objects, embodiments, and the long tail of real-world environments.",
      accent: "amber",
    },
    {
      id: 3,
      kicker: "03 · Trust",
      title: "Safe autonomy",
      description:
        "Uncertainty-aware policies and evaluation tools for robots that remain dependable around people.",
      accent: "ink",
    },
  ],
  people: [
    {
      id: 1,
      name: "Dr. Xiaodong Yue",
      role: "Principal Investigator",
      group: "Faculty",
      bio: "Xiaodong leads the lab's work on learning-based control and trustworthy autonomy.",
      research_interests: ["Robot learning", "Safe control", "World models"],
      email: "lin.zhao@motionlab.example",
      website_url: "https://example.com",
      avatar_url: "/Xiaodong-transparent.png",
    },
    {
      id: 2,
      name: "Maya Chen",
      role: "PhD Student",
      group: "Students",
      bio: "Maya studies active data collection for dexterous manipulation.",
      research_interests: ["Manipulation", "Active learning"],
      email: "maya.chen@motionlab.example",
    },
    {
      id: 3,
      name: "Ethan Wu",
      role: "PhD Student",
      group: "Students",
      bio: "Ethan works on calibrated uncertainty for robot planning.",
      research_interests: ["Planning", "Uncertainty"],
      email: "ethan.wu@motionlab.example",
    },
    {
      id: 4,
      name: "Aria Patel",
      role: "Research Engineer",
      group: "Research staff",
      bio: "Aria builds the hardware and software systems behind our experiments.",
      research_interests: ["Systems", "Hardware"],
      email: "aria.patel@motionlab.example",
    },
    {
      id: 5,
      name: "Noah Kim",
      role: "Visiting Student",
      group: "Students",
      bio: "Noah explores multimodal policies for mobile manipulation.",
      research_interests: ["Vision-language", "Mobile robots"],
      email: "noah.kim@motionlab.example",
    },
  ],
  publications: [
    {
      id: 1,
      title: "Safe Policy Improvement with Calibrated World Models",
      authors: "M. Chen, E. Wu, L. Zhao",
      venue: "Robotics: Science and Systems",
      venue_short: "RSS",
      year: 2026,
      type: "Conference",
      status: "Published",
      abstract:
        "A practical framework for using predictive world models while explicitly accounting for model uncertainty.",
      paper_url: "#",
      pdf_url: "#",
      code_url: "#",
      video_url: "#",
      featured: true,
    },
    {
      id: 2,
      title: "Learning Contact-Rich Skills from Short Robot Play Sessions",
      authors: "A. Patel, M. Chen, L. Zhao",
      venue: "IEEE International Conference on Robotics and Automation",
      venue_short: "ICRA",
      year: 2026,
      type: "Conference",
      status: "Published",
      abstract:
        "A data-efficient approach to adapting manipulation policies to new objects and embodiments.",
      paper_url: "#",
      pdf_url: "#",
      code_url: "#",
      featured: false,
    },
    {
      id: 3,
      title: "A Benchmark for Human-Centered Robot Reliability",
      authors: "N. Kim, E. Wu, L. Zhao",
      venue: "arXiv preprint",
      venue_short: "arXiv",
      year: 2025,
      type: "Preprint",
      status: "Preprint",
      abstract:
        "A reproducible evaluation suite for measuring whether learned robot policies know when to ask for help.",
      paper_url: "#",
      pdf_url: "#",
      code_url: "#",
      featured: false,
    },
  ],
};
